openapi: 3.0.0
info:
  title: Hello World API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Get a greeting message
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              example:
                message: Hello, World!
